version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    working_directory: ~/Users/wonderland/CircleCITestiOS
    environment:
      FASTLANE_LANE: all
    shell: /bin/bash --login
    steps:
      - checkout
      - run:
          command: base64 -D -o Certificates.p12 <<< $Certificates
      - run:
          command: mkdir -pv ~/Library/MobileDevice/Provisioning\ Profiles/
      - run:
          command: base64 -D -o ~/Library/MobileDevice/Provisioning\ Profiles/App_Store.mobileprovision <<< $App_Store_Profile
      - run:
          working_directory: ~/yourProyect/whatever
          command: bundle install
      - run:
          working_directory: ~/Users/wonderland/CircleCITestiOS/whatever
          command: bundle exec fastlane $FASTLANE_LANE circleci:true

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test